apiVersion: apps/v1
kind: Deployment
metadata:
  name: vudugf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vudugf
  template:
    metadata:
      labels:
        app: vudugf
    spec:
      containers:
      - image: okteto.dev/vudugf:latest
        name: vudugf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3e2dbb2a-85e0-419c-a00c-4f5784724721"
        - name: Vless_Path
          value: "/vl5nwr55"
        - name: Vmess_UUID
          value: "3e2dbb2a-85e0-419c-a00c-4f5784724721"
        - name: Vmess_Path
          value: "/vm6eg66"
        - name: Share_Path
          value: "/v2link"
